language: bash

matrix:
  include:
    - name: "MSVC on Windows"
      os: windows
      env:
        - MSBUILD_PATH="c:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin"
      # solution: msvc-gtest-codecov-test.sln
      # install:
      #  - nuget restore msvc-gtest-codecov-test.sln
      script:
        - export PATH=$MSBUILD_PATH:$PATH
        - MSBuild.exe /p:Configuration=Release msvc-gtest-codecov-test.sln
