language: cpp
dotnet: 2.1.502
os: windows

env:
  - MSBUILD_PATH="c:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin"
  - CODECOV_TOKEN="af7c1dd4-adcf-44b8-b0d9-bcc72f30c0c9"
# solution: msvc-gtest-codecov-test.sln

install:
  - choco install nuget.commandline
  - nuget restore msvc-gtest-codecov-test.sln
#  - dotnet restore
#  - dotnet build
#  - dotnet run
#  - nuget restore msvc-gtest-codecov-test.sln

script:
  - export PATH=$MSBUILD_PATH:$PATH
  - MSBuild.exe msvc-gtest-codecov-test.sln
  - ./x64/Debug/GoogleTest.exe

after_success:
  - bash <(curl -s https://codecov.io/bash)
