language: bash
os: windows

env:
  - MSBUILD_PATH="c:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin"
# solution: msvc-gtest-codecov-test.sln

install:
  - choco install nuget.commandline --pre
  #- choco install codecov
  - nuget restore msvc-gtest-codecov-test.sln

script:
  - export PATH=$MSBUILD_PATH:$PATH
  - MSBuild.exe msvc-gtest-codecov-test.sln
  - ./x64/Debug/GoogleTest.exe > ./test.log
  - cat ./test.log

after_success:
  - bash <(curl -s https://codecov.io/bash)
